# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/dependabot-2.0.json

version: 2
updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: daily
      time: '02:00'
    ignore:
      - dependency-name: none

  - package-ecosystem: pip
    directory: '/example-project'
    schedule:
      interval: daily
      time: '02:00'
    ignore:
      - dependency-name: none

  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: daily
      time: '02:00'
    ignore:
      - dependency-name: none

  - package-ecosystem: docker
    directory: '/example-project'
    schedule:
      interval: daily
      time: '02:00'
    ignore:
      - dependency-name: none

  - package-ecosystem: npm
    directory: '/test'
    schedule:
      interval: daily
      time: '02:00'
    ignore:
      - dependency-name: none
