version: 2
updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: daily
      time: '02:00'
    open-pull-requests-limit: 99
    allow:
      - dependency-type: direct

  - package-ecosystem: pip
    directory: '/example-project'
    schedule:
      interval: daily
      time: '02:00'
    open-pull-requests-limit: 99
    allow:
      - dependency-type: direct
