---
name: Auto merge Dependabot updates

on:
  check_suite:
    types:
      - completed
  pull_request:
    types:
      - opened
  workflow_run:
    workflows:
      - Continuous integration
      - CodeQL scanning
    types:
      - completed

jobs:
  auto-merge:
    name: Auto merge Dependabot updates
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Auto merge
        uses: sbrunner/merge-me-action@workflow_run_dist
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_LOGIN: dependabot[bot]
